version: "3.9"
services:
  worker: /lib/Dockerfile
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
